version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres_finance
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mock-saldo:
    image: mock-saldo-api
    container_name: mock_saldo_api
    ports:
      - "3001:3001"
    restart: always

volumes:
  postgres-data:
