version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres_finance
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mock-saldo:
    image: mock-saldo-api
    container_name: mock_saldo_api
    ports:
      - "3001:3001"
    restart: always

  api:
    build: .
    container_name: gestao_financeira_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mock-saldo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SALDO_API_URL: http://mock-saldo:3001
    restart: always

volumes:
  postgres-data:
